trigger: none

pr:
  branches:
    include:
      - development

variables:
  frontendArtifactName: frontend
  deploymentFile: $(frontendArtifactName)-$(Build.BuildId).zip

stages:
- stage: build
  displayName: Build frontend server
  jobs:
  - template: templates/build-job-pipeline.yml
    parameters:
      artifactName: $(frontendArtifactName)
      deploymentFile: $(deploymentFile)
- stage: deployDev
  displayName: Deploy development environment
  jobs:
  - template: templates/deploy-stage-pipeline.yml
    parameters:
      environment: development
      resourceSufix: -dev
      artifactName: $(frontendArtifactName)
      deploymentFile: $(deploymentFile)
- stage: deployProd
  displayName: Deploy production environment
  condition: and(succeeded(), eq(variables['System.PullRequest.TargetBranch'], 'refs/heads/master'))
  jobs:
  - template: templates/deploy-stage-pipeline.yml
    parameters:
      environment: production
      resourceSufix: ''
      artifactName: $(frontendArtifactName)
      deploymentFile: $(deploymentFile)