// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: false,
  hmr: true,
  version: env.npm_package_version + '-dev',
  defaultLanguage: 'pt-BR',
  supportedLanguages: ['pt-BR'],
  serverUrl: '/',
  apiKey: 'AIzaSyDfWbHv7mPzO8TPuYi2PPvTZ_KXfL9UYF4',
  spreadsheetIdRitos: '19ZBFnBBTBPInGoXyVf2ImRm4d9IUYv_h2jELR1jTKfA',
  spreadsheetIdConfiguracoes: '1mMKvGX49js5-Z1JBq_3tBuPdtPclDwo3L7abbLBnuO4',
  spreadsheetIdBurndown: '108jumL8Xylg4iApCxt7ywWnYo6HM1pMip4l9IitKYCI',
  rangeFatosRelevantes: 'Fatos Relevantes',
  rangeBurndown: 'Burndown GAV',
  rangeAcoes: 'Ações GAV',
  rangeSpreadsheetId: 'squads',
  rangeEventos: 'eventos',
  tempoAtualizacao: 600000,
  oneOnOne: 'http://one-on-ones-dti.herokuapp.com/api/data_tribe/{tribo}'
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
