// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  hmr: false,
  version: env.npm_package_version,
  defaultLanguage: 'pt-BR',
  serverUrl: '/',
  supportedLanguages: ['pt-BR'],
  apiKey: 'AIzaSyD6lCuBziMzN3yWvrNnd7WxZoKXUChca4I',
  spreadsheetIdRitos: '19ZBFnBBTBPInGoXyVf2ImRm4d9IUYv_h2jELR1jTKfA',
  spreadsheetIdConfiguracoes: '1mMKvGX49js5-Z1JBq_3tBuPdtPclDwo3L7abbLBnuO4',
  spreadsheetIdBurndown: '108jumL8Xylg4iApCxt7ywWnYo6HM1pMip4l9IitKYCI',
  rangeFatosRelevantes: 'Fatos Relevantes',
  rangeBurndown: 'Burndown GAV',
  rangeAcoes: 'Ações GAV',
  rangeSpreadsheetId: 'squads',
  rangeEventos: 'eventos',
  tempoAtualizacao: 600000,
  oneOnOne: 'http://one-on-ones-dti.herokuapp.com/api/data_tribe/{tribo}'
};
