parameters:
  artifactName: ''
  deploymentFile: ''

jobs:
- job:
  displayName: Building frontend
  steps:
  - task: NodeTool@0
    displayName: Install Node.js
    inputs:
      versionSpec: 10.x
  - task: Npm@1
    displayName: Install dependencies
    inputs:
      command: install
  - task: Npm@1
    displayName: Build Frontend
    inputs:
      command: custom
      customCommand: run build
  - task: ArchiveFiles@2
    displayName: Archive builded code
    inputs:
      rootFolderOrFile: dist
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/${{parameters.deploymentFile}}
      replaceExistingArchive: true
  - publish: $(Build.ArtifactStagingDirectory)/${{parameters.deploymentFile}}
    displayName: Publish Archived artifact
    artifact: ${{parameters.artifactName}}