parameters:
  environment: development
  webAppName: ''
  artifactName: ''
  deploymentFile: ''

jobs:
- deployment:
  displayName: Deploying ${{parameters.environment}}
  environment: ${{parameters.environment}}
  condition: succeeded()
  strategy:
    runOnce:
      deploy:
        steps:
        - bash: |
            if [ -z "$WEB_APP_NAME" ]; then
              echo "##vso[task.logissue type=error;]Missing template parameter \"webAppName\""
              echo "##vso[task.complete result=Failed;]"
            fi
            if [ -z "$ARTIFACT_NAME" ]; then
              echo "##vso[task.logissue type=error;]Missing template parameter \"artifactName\""
              echo "##vso[task.complete result=Failed;]"
            fi
            if [ -z "$DEPLOYMENT_FILE" ]; then
              echo "##vso[task.logissue type=error;]Missing template parameter \"deploymentFile\""
              echo "##vso[task.complete result=Failed;]"
            fi
          displayName: Checking mandatory parameters
          env:
            WEB_APP_NAME: ${{parameters.webAppName}}
            ARTIFACT_NAME: ${{parameters.artifactName}}
            DEPLOYMENT_FILE: ${{parameters.deploymentFile}}
        - task: AzureRmWebAppDeployment@4
          displayName: 'Deploy frontend on Azure App Service'
          inputs:
            azureSubscription: 'terraformagent-connection'
            appType: 'webApp'
            WebAppName: '${{parameters.webAppName}}'
            packageForLinux: '$(Pipeline.Workspace)/${{parameters.artifactName}}/${{parameters.deploymentFile}}'
