parameters:
  environment: development
  resourceSufix: ''
  artifactName: ''
  deploymentFile: ''

jobs:
- template: infrastructure-job-pipeline.yml
  parameters:
    resourcePrefix: gestaoavistadti${{parameters.resourceSufix}}
    environment: ${{parameters.environment}}
- template: deployment-job-pipeline.yml
  parameters:
    environment: ${{parameters.environment}}
    webAppName: gestaoavistadti${{parameters.resourceSufix}}
    artifactName: ${{parameters.artifactName}}
    deploymentFile: ${{parameters.deploymentFile}}
